# Modelle und Adapter-Zuordnung
models:
  - name: gpt-4.1
    provider: openai
    adapter: openai_gpt
  - name: claude-sonnet-4-20250514
    provider: anthropic
    adapter: anthropic_claude
  - name: grok-4-0709
    provider: xai
    adapter: xai_grok
  - name: ministral-3b-2410
    provider: local
    adapter: local_mistral
  # - name: Teuken-7B-instruct-v0.6
  #   provider: local
  #   adapter: local_teuken
  #   params:
  #     temperature: 0.7
  #     top_p: 0.95
  #     max_tokens: 400

# Separates Judge-Modell (hier rein logisch getrennt, im Code deterministisch)
judge:
  name: Judge-Det
  provider: local
  temperature: 0.0
