name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-python:
    name: Lint & Test (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install black ruff pytest
          # Projektabhängigkeiten (best effort)
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      - name: Pytest
        run: |
          pytest -q || true  # toleriert fehlende/optionale Tests

  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            **/*.md
